# Name: Justin Barlowe
# Title: barlowe-composers.yaml
# Description: YAML file for composers API
# Date: 8/24/2023

# Specify the OpenAPI version and info
openapi: 3.0.0
info:
  title: Composers API
  version: 1.0.0

# Tags to operations
tags:
  - name: Composers

# API Paths
paths:
  /api/composers:
  # GET operation for all composers
    get:
      tags:
        - Composers
      summary: Retrieve all composers
      responses:
        '200':
          description: Successful operation
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception
    # POST operation for creating a composer
    post:
      tags:
        - Composers
      summary: Create a composer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
      responses:
        '200':
          description: Successful operation
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception
  # GET operation for a specific composer by ID
  /api/composers/{id}:
    get:
      tags:
        - Composers
      summary: Retrieve composer by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception
